### ISSUE TITLE
Apparant bug in mesido 0.1.5.1

### ISSUE THREAD

**Issue by KobusVanRooyen** [Multi-Energy-Systems-Optimization/mesido#107]
Email from Sebs:

Today I worked on updating OMOTES to work with mesido 0.1.5.1 but unfortunately I have hit a snag. It appears I found a bug.
If you run the attached test script (remove the .txt extension) with mesido 0.1.5.1, it results in an exception:

Traceback (most recent call last):
  File "/home/sebastiaan/repositories/nieuwe-warmte-nu/mesido/test.py", line 39, in <module>
    print(solution.optimized_esdl_string)
AttributeError: 'EndScenarioSizingDiscountedStagedHIGHS' object has no attribute 'optimized_esdl_string'

Diving a little into the code, it has to do with the fact that mesido.workflows.grow_workflow.py::EndScenarioSizing.post only writes out the result if self._stage == 2 or self._stage does not exist.
However, in this case, self._stage == 1. As is described in the attached testing script, we are calling mesido with ‘run_end_scenario_sizing_no_heat_losses’ as the problem function
and ‘EndScenarioSizingDiscountedStagedHIGHS’ as the problem class (which translates to the ‘grow_optimizer_no_heat_losses’ worker type).

This commit introduces this change: https://github.com/Multi-Energy-Systems-Optimization/mesido/commit/ec6c470b46280e077d1e157c6e4951ffcf83dac4 

Could you please advise if we are using mesido wrong or if this is a bug?

**Comment by KobusVanRooyen** [comment]
This was already resolved in main, tag 0.1.5.1 was not updated. Now it has been updated in tag 0.1.5.2
